import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Providers from '@/components/providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <Providers>
        <body className={inter.className}>
          <div className="grid min-h-screen grid-rows-[auto_1fr_auto]">
            <div className="bg-slate-500">headers go here</div>
            <div>{children}</div>
            <div className="bg-slate-500">footers go here</div>
          </div>
        </body>
      </Providers>
    </html>
  )
}
